###################################################################################################

- name: verify

  assert:
    that:

      - lvm_volume_name is defined
      - lvm_volume_name is not none
      - lvm_volume_name | trim | length > 0

      - lvm_volume_group is defined
      - lvm_volume_group is not none
      - lvm_volume_group | trim | length > 0

  tags:
    - artemis
    - volume
    - lvm
    - volume

###################################################################################################

- name: volume

  become: true

  lvol: lv={{ lvm_volume_name  }}
        vg={{ lvm_volume_group }}
      size={{ lvm_volume_size  }}
     state={{ lvm_volume_state }}
     force={{ lvm_volume_force }}

  tags:
    - artemis
    - volume
    - lvm
    - volume

###################################################################################################
