###################################################################################################

- name: verify

  when: hosts

  assert:
    that:

      - host_name is defined
      - host_name is not none
      - host_name | trim | length > 0

      - host_domain is defined
      - host_domain is not none
      - host_domain | trim | length > 0

  tags:
    - artemis
    - platform
    - hosts

###################################################################################################

- name: configure

  when: hosts

  become: true

  template: src={{ hosts_src  }}
           dest={{ hosts_dest }}
           mode={{ hosts_mode }}

  register: configure

  tags:
    - artemis
    - platform
    - hosts

###################################################################################################

- name: setup

  when: configure.changed

  setup:

  tags:
    - artemis
    - platform
    - hosts

###################################################################################################
