###################################################################################################

- name: import | family

  when: os_family_is_debian
     or os_family_is_redhat

  include_vars: '{{ os_family_lower }}{{ yaml_file_extension }}'

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: verify

  assert:
    that:

      - mac_security is not none
      - mac_security | trim | length > 0

  tags:
    - artemis
    - platform
    - mac

###################################################################################################

- name: family

  when: os_family_is_debian
     or os_family_is_redhat

  include: '{{ os_family_lower }}{{ yaml_file_extension }}'
  static : false

  tags:
    - artemis
    - platform
    - mac

###################################################################################################
