###################################################################################################

- name: import | release

  include_vars: '{{ item }}'

  with_first_found:
    - '{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}'
    - '{{ dev_null }}'

  tags:
    - artemis
    - platform
    - timezone

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - timezone

###################################################################################################

- name: ubuntu | 14

  when: ansible_distribution               | lower == 'ubuntu'
    and ansible_distribution_major_version | lower == '14'

  include: ubuntu-14.yml
  static : false

  tags:
    - artemis
    - platform
    - timezone

###################################################################################################

- name: systemd

  when: ansible_distribution               | lower != 'ubuntu'
     or ansible_distribution_major_version | lower != '14'

  include: systemd.yml
  static : false

  tags:
    - artemis
    - platform
    - timezone

###################################################################################################
